name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
# WORKFLOW SCOPE/LEVEL VARIABLES PLACED HERE
env:
  NAME: 'SHAWN DEMO'
  
jobs:
  build:
    runs-on: ubuntu-latest
    # JOB SCOPE/LEVEL VARIABLES PLACED HERE
    env:
      JAVA_VER: '21'
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ env.JAVA_VER }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VER }}
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Print name
      run: echo "Hello $NAME"
    - name: Print JAVA VERSION
      run: echo "We are doing build # $BUILD using Java Version $JAVA_VER"
      env:
        BUILD: "Build3221"
